<div class="markdown-text"><p><img src="https://user-images.githubusercontent.com/23253540/146678508-48e8fa8a-835f-4735-b9ab-c04d540c108b.png" alt="image"></p>
<p>hi, all ～ 分享一个批量项目迁移到 pnpm 过程中遇到的问题与解决办法，希望对大家有所帮助 ~
原文链接: <a href="https://github.com/xiaoxiaojx/blog/issues/23">https://github.com/xiaoxiaojx/blog/issues/23</a></p>
<h2>背景</h2>
<p>在 <a href="https://www.zhihu.com/question/493891614/answer/2268212740">2022 前端技术领域会有哪些新的变化？</a> 话题中我曾回答到，越来越多的项目会开始使用 pnpm 。</p>
<blockquote>
<p>这是我正在推动的一件事，使用 pnpm 替换现在的 yarn 。无论是 csr 、ssr 、monorepos 等类型项目都正在进行中，有近 10 个项目已经迁移完成。
当时 yarn 的 pnp 特性出来的时候，观望过一阵子，没有大面积火起来，遂放弃 …
现在是注意到 vite 、modernjs 等使用了 pnpm ，其设计理念与 node_modules 的目录结构也能让业务更加快速安全，所以决定开始全面使用 pnpm 。</p>
</blockquote>
<p>下面记录与分享一下最近使用 pnpm 遇到的问题与解决的过程~</p>
<h2>✅ 已解决的问题</h2>
<h3>jest 单测运行失败</h3>
<ul>
<li>问题描叙: 使用 pnpm 后，原有的 jest 单测失败了</li>
<li>问题解决: jest 低版本不支持软链接, 升级 jest 大于等于 25.2.0 版本即可</li>
<li>报错信息:
<img src="https://user-images.githubusercontent.com/23253540/146667443-8fe7609d-8659-4973-8566-c04d2f9d4778.png" alt="ca958dffa2ef75ad06f068262b471a7ea952fc25"></li>
<li>问题分析:
<ol>
<li>根据报错的堆栈找到报错的包，发现其 packge.json dependencies 字段明确声明了依赖的 <a href="/user/xxx">@xxx</a>/fetch 的版本。但是从报错的信息看，实际运行测试时 import 的却是错误的版本了!</li>
<li>这里就需要思考一下 jest 是如何运行一个单测用例。如果是简单的 node xxx.test.js 运行一个单测那就不会有上面引用到错误版本依赖的问题，因为按照 node require 模块的规则是不会解析出错。</li>
<li>让我们回头看一个简单的 jest 单测用例，可以大胆推测一下每个 describe 或者是 it 语句就是一个单独的沙盒环境。如果简单的运行 node xxx.test.js 那就只会存在一个沙盒环境，所有的测试用例会共用一个上下文，这样明显不利于 jest 每个单测隔离的原则</li>
<li>所以我们初步判断 jest 会自己创建若干个沙盒环境去运行对应的测试代码。而用户的 src 待测试的代码在 jest 看来会通过 fs.readFileSync 去获取到内容字符串，然后不同类型文件经过 babelTransform 或者 tsTransform 得到 js 代码，最后通过 vm 或者 eval, new Function 这样去运行。</li>
<li>所以说代码中的 import require 等语句的路径是 jest 去静态分析补充完整的，低版本的 jest resolve 不支持软链接是完全有可能的，所以我们顺着 jest 的发版日志，找到最近支持软链接的版本问题解决。</li>
<li>同理 nextjs 等项目如果有问题也需要找到最近支持软链接的版本进行升级</li>
</ol>
</li>
</ul>
<pre class="prettyprint language-js"><code>&#x2F;&#x2F; Copyright 2004-present Facebook. All Rights Reserved.

&#x27;use strict&#x27;;

jest.useFakeTimers();

describe(&#x27;timerGame&#x27;, () =&gt; {
  beforeEach(() =&gt; {
    jest.spyOn(global, &#x27;setTimeout&#x27;);
  });
  it(&#x27;waits 1 second before ending the game&#x27;, () =&gt; {
    const timerGame = require(&#x27;..&#x2F;timerGame&#x27;);
    timerGame();

    expect(setTimeout).toBeCalledTimes(1);
    expect(setTimeout).toBeCalledWith(expect.any(Function), 1000);
  });

  it(&#x27;calls the callback after 1 second via runAllTimers&#x27;, () =&gt; {
    const timerGame = require(&#x27;..&#x2F;timerGame&#x27;);
    const callback = jest.fn();

    timerGame(callback);

    &#x2F;&#x2F; At this point in time, the callback should not have been called yet
    expect(callback).not.toBeCalled();

    &#x2F;&#x2F; Fast-forward until all timers have been executed
    jest.runAllTimers();

    &#x2F;&#x2F; Now our callback should have been called!
    expect(callback).toBeCalled();
    expect(callback).toBeCalledTimes(1);
  });
});
</code></pre><h3>node-gyp rebuild failures</h3>
<ul>
<li>问题描叙: 使用 pnpm 后，项目中依赖的 Node.js C++ 插件 rebuild 失败</li>
<li>问题解决: pnpm 低版本 bug ，升级 pnpm 大于等于 6.23.1 版本即可，相关 issue <a href="https://github.com/pnpm/pnpm/issues/2135">issues/2135</a></li>
<li>报错信息:</li>
</ul>
<pre class="prettyprint language-bash"><code># pnpm i better-sqlite3
Packages: +11
+++++++++++
Resolving: total 11, reused 11, downloaded 0, done
node_modules&#x2F;.pnpm&#x2F;registry.npmjs.org&#x2F;integer&#x2F;2.1.0&#x2F;node_modules&#x2F;integer: Running install script, done in 2s
node_modules&#x2F;.pnpm&#x2F;registry.npmjs.org&#x2F;better-sqlite3&#x2F;5.4.3&#x2F;node_modules&#x2F;better-sqlite3: Running install script, failed in 393ms
...&#x2F;5.4.3&#x2F;node_modules&#x2F;better-sqlite3 install$ node-gyp rebuild
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@6.0.0
│ gyp info using node@12.13.0 | linux | x64
│ gyp info find Python using Python version 3.6.8 found at &quot;&#x2F;usr&#x2F;bin&#x2F;python3&quot;
│ gyp info spawn &#x2F;usr&#x2F;bin&#x2F;python3
│ gyp info spawn args [
│ gyp info spawn args   &#x27;&#x2F;usr&#x2F;lib&#x2F;node_modules&#x2F;pnpm&#x2F;lib&#x2F;node_modules&#x2F;node-gyp&#x2F;gyp&#x2F;gyp_main.py&#x27;,
│ gyp info spawn args   &#x27;binding.gyp&#x27;,
│ gyp info spawn args   &#x27;-f&#x27;,
│ gyp info spawn args   &#x27;make&#x27;,
│ gyp info spawn args   &#x27;-I&#x27;,
│ gyp info spawn args   &#x27;&#x2F;root&#x2F;2&#x2F;node_modules&#x2F;.pnpm&#x2F;registry.npmjs.org&#x2F;better-sqlite3&#x2F;5.4.3&#x2F;node_modules&#x2F;better-sqlite3&#x2F;build&#x2F;config.gypi&#x27;,
│ gyp info spawn args   &#x27;-I&#x27;,
│ gyp info spawn args   &#x27;&#x2F;usr&#x2F;lib&#x2F;node_modules&#x2F;pnpm&#x2F;lib&#x2F;node_modules&#x2F;node-gyp&#x2F;addon.gypi&#x27;,
│ gyp info spawn args   &#x27;-I&#x27;,
│ gyp info spawn args   &#x27;&#x2F;root&#x2F;.cache&#x2F;node-gyp&#x2F;12.13.0&#x2F;include&#x2F;node&#x2F;common.gypi&#x27;,
│ gyp info spawn args   &#x27;-Dlibrary=shared_library&#x27;,
│ gyp info spawn args   &#x27;-Dvisibility=default&#x27;,
│ gyp info spawn args   &#x27;-Dnode_root_dir=&#x2F;root&#x2F;.cache&#x2F;node-gyp&#x2F;12.13.0&#x27;,
│ gyp info spawn args   &#x27;-Dnode_gyp_dir=&#x2F;usr&#x2F;lib&#x2F;node_modules&#x2F;pnpm&#x2F;lib&#x2F;node_modules&#x2F;node-gyp&#x27;,
│ gyp info spawn args   &#x27;-Dnode_lib_file=&#x2F;root&#x2F;.cache&#x2F;node-gyp&#x2F;12.13.0&#x2F;&lt;(target_arch)&#x2F;node.lib&#x27;,
│ gyp info spawn args   &#x27;-Dmodule_root_dir=&#x2F;root&#x2F;2&#x2F;node_modules&#x2F;.pnpm&#x2F;registry.npmjs.org&#x2F;better-sqlite3&#x2F;5.4.3&#x2F;node_modules&#x2F;better-sqlite3&#x27;,
│ gyp info spawn args   &#x27;-Dnode_engine=v8&#x27;,
│ gyp info spawn args   &#x27;--depth=.&#x27;,
│ gyp info spawn args   &#x27;--no-parallel&#x27;,
│ gyp info spawn args   &#x27;--generator-output&#x27;,
│ gyp info spawn args   &#x27;build&#x27;,
│ gyp info spawn args   &#x27;-Goutput_dir=.&#x27;
│ gyp info spawn args ]
│ Traceback (most recent call last):
│   File &quot;&#x2F;usr&#x2F;lib&#x2F;node_modules&#x2F;pnpm&#x2F;lib&#x2F;node_modules&#x2F;node-gyp&#x2F;gyp&#x2F;gyp_main.py&quot;, line 50, in &lt;module&gt;
│     sys.exit(gyp.script_main())
│   File &quot;&#x2F;usr&#x2F;lib&#x2F;node_modules&#x2F;pnpm&#x2F;lib&#x2F;node_modules&#x2F;node-gyp&#x2F;gyp&#x2F;pylib&#x2F;gyp&#x2F;__init__.py&quot;, line 554, in script_main
│     return main(sys.argv[1:])
│   File &quot;&#x2F;usr&#x2F;lib&#x2F;node_modules&#x2F;pnpm&#x2F;lib&#x2F;node_modules&#x2F;node-gyp&#x2F;gyp&#x2F;pylib&#x2F;gyp&#x2F;__init__.py&quot;, line 547, in main
│     return gyp_main(args)
│   File &quot;&#x2F;usr&#x2F;lib&#x2F;node_modules&#x2F;pnpm&#x2F;lib&#x2F;node_modules&#x2F;node-gyp&#x2F;gyp&#x2F;pylib&#x2F;gyp&#x2F;__init__.py&quot;, line 532, in gyp_main
│     generator.GenerateOutput(flat_list, targets, data, params)
│   File &quot;&#x2F;usr&#x2F;lib&#x2F;node_modules&#x2F;pnpm&#x2F;lib&#x2F;node_modules&#x2F;node-gyp&#x2F;gyp&#x2F;pylib&#x2F;gyp&#x2F;generator&#x2F;make.py&quot;, line 2215, in GenerateOutput
│     part_of_all=qualified_target in needed_targets)
│   File &quot;&#x2F;usr&#x2F;lib&#x2F;node_modules&#x2F;pnpm&#x2F;lib&#x2F;node_modules&#x2F;node-gyp&#x2F;gyp&#x2F;pylib&#x2F;gyp&#x2F;generator&#x2F;make.py&quot;, line 794, in Write
│     extra_mac_bundle_resources, part_of_all)
│   File &quot;&#x2F;usr&#x2F;lib&#x2F;node_modules&#x2F;pnpm&#x2F;lib&#x2F;node_modules&#x2F;node-gyp&#x2F;gyp&#x2F;pylib&#x2F;gyp&#x2F;generator&#x2F;make.py&quot;, line 978, in WriteActions
│     part_of_all=part_of_all, command=name)
│   File &quot;&#x2F;usr&#x2F;lib&#x2F;node_modules&#x2F;pnpm&#x2F;lib&#x2F;node_modules&#x2F;node-gyp&#x2F;gyp&#x2F;pylib&#x2F;gyp&#x2F;generator&#x2F;make.py&quot;, line 1724, in WriteDoCmd
│     force = True)
│   File &quot;&#x2F;usr&#x2F;lib&#x2F;node_modules&#x2F;pnpm&#x2F;lib&#x2F;node_modules&#x2F;node-gyp&#x2F;gyp&#x2F;pylib&#x2F;gyp&#x2F;generator&#x2F;make.py&quot;, line 1779, in WriteMakeRule
│     cmddigest = hashlib.sha1(command if command else self.target).hexdigest()
│ TypeError: Unicode-objects must be encoded before hashing
│ gyp ERR! configure error
│ gyp ERR! stack Error: &#96;gyp&#96; failed with exit code: 1
│ gyp ERR! stack     at ChildProcess.onCpExit (&#x2F;usr&#x2F;lib&#x2F;node_modules&#x2F;pnpm&#x2F;lib&#x2F;node_modules&#x2F;node-gyp&#x2F;lib&#x2F;configure.js:351:16)
│ gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
│ gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal&#x2F;child_process.js:272:12)
│ gyp ERR! System Linux 4.15.0-33-generic
│ gyp ERR! command &quot;&#x2F;usr&#x2F;bin&#x2F;node&quot; &quot;&#x2F;usr&#x2F;lib&#x2F;node_modules&#x2F;pnpm&#x2F;lib&#x2F;node_modules&#x2F;node-gyp&#x2F;bin&#x2F;node-gyp.js&quot; &quot;rebuild&quot;
│ gyp ERR! cwd &#x2F;root&#x2F;2&#x2F;node_modules&#x2F;.pnpm&#x2F;registry.npmjs.org&#x2F;better-sqlite3&#x2F;5.4.3&#x2F;node_modules&#x2F;better-sqlite3
│ gyp ERR! node -v v12.13.0
│ gyp ERR! node-gyp -v v6.0.0
│ gyp ERR! not ok
└─ Failed in 393ms
 ERROR  Command failed with exit code 1.
</code></pre><ul>
<li>问题分析: 会不会是 c++ 版本的问题？而得到的信息为该镜像使用 yarn 却是好的! 最终换了同一个 Node.js 版本的镜像又好了，辗转反侧才在 pnpm 的 issue 中找到真正的原因，为 pnpm 低版本的 bug 。</li>
</ul>
<h3>同一个版本的包有两份副本</h3>
<ul>
<li>问题描述: 同一个版本的包在 .pnpm 目录下却有两份副本</li>
<li>问题解决: 添加 .pnpmfile.cjs 文件，忽略 peerDependencies ，使其对 peer 的处理与 yarn 保持一致</li>
</ul>
<pre class="prettyprint language-js"><code>&#x2F;&#x2F; .pnpmfile.cjs

function readPackage(pkg, context) {
  if (pkg.name &amp;&amp; pkg.peerDependencies) {
    &#x2F;&#x2F; https:&#x2F;&#x2F;pnpm.io&#x2F;zh&#x2F;how-peers-are-resolved
    pkg.peerDependencies = {}
  }

  return pkg
}

module.exports = {
  hooks: {
    readPackage,
  },
}

</code></pre><ul>
<li>报错信息:
<img src="https://user-images.githubusercontent.com/23253540/143979554-083009de-e027-461a-aa85-1c982491e043.png" alt="img"></li>
<li>问题分析: 这个问题困扰了很久，后仔细阅读了 pnpm 的 <a href="https://www.pnpm.cn/how-peers-are-resolved">How peers are resolved</a> 文档，确认了造成的原因。详细的讨论可见: <a href="https://github.com/pnpm/pnpm/discussions/4051">discussions/4051</a></li>
</ul>
<h3>only-allow 命令影响到了业务项目</h3>
<ul>
<li>问题描叙: 当你在一个公共包的项目中添加了 preinstall 的勾子，但是实际依赖该包的业务并未使用 pnpm ，造成报错</li>
<li>问题解决: only-allow 当作为依赖时不应该进行检查，暂时使用支持了该功能的 only-allow-test 包代替。对应的讨论见 : <a href="https://github.com/pnpm/pnpm/discussions/4131">discussions/4131</a></li>
</ul>
<pre class="prettyprint language-json"><code>{
    &quot;scripts&quot;: {
        &quot;preinstall&quot;: &quot;npx only-allow pnpm&quot;
    }
}
</code></pre><h2>❌ 未解决的问题</h2>
<h3>pnpm add 与 pnpm i 命令不会去重</h3>
<ul>
<li>问题描叙: 当使用 pnpm add 或者 pnpm i 升级某个包时，会存在某几个版本兼容的包没有进行合并，导致存在多个版本。如 sass: ^1.30.0 和 sass: '^1.44.0’没有被合并，但是使用 pnpm update 去升级这个包是会进行合并</li>
<li>问题分析: 由于使用 yarn 的习惯不小心就会发生这种情况，所以希望支持 pnpm deduplicate 去重的命令，每次构建前强制运行一次，反馈后作者表示 pnpm add 命令会保持和 update 命令同样的行为。对应的讨论见 <a href="https://github.com/pnpm/pnpm/discussions/4143">discussions/4143</a></li>
</ul>
<h3>cypress e2e 测试运行失败</h3>
<ul>
<li>问题描叙: 使用 pnpm 后，原有的 cypress e2e 测试失败了</li>
<li>问题分析: 经过 debug 发现 cypress 还不支持 pnpm, 于是提了一个 <a href="https://github.com/cypress-io/cypress/pull/19189">pr</a>，cypress 处理跟进较慢，还未解决</li>
</ul>
</div>